name: Publish resume

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      - name: Rename output
        run: mv main.pdf Matthias-Green-Resume.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"
      - name: GH Release
        uses: softprops/action-gh-release@v2.4.1
        with:
          name: "${{ github.ref_name }}"
          files: Matthias-Green-Resume.pdf
